### ISSUE TITLE
SUSSUDIO: alternative keyframer select mode

### ISSUE THREAD

**Issue by Eurikon** [nysthi/nysthi#315] opened 2020-10-15 11:12 UTC
Hi Antonio,
currently when we select a different key-frame, the play-heads will jump back to the start position of the newly selected frame.

Can we have an alternative mode, in which the play-heads continue playing where they are at in the newly selected frame?

Cheers,
Latif

**Comment by nysthi** [comment] 2020-10-15 16:58
Ciao @Eurikon I'll check if it's doable

(the problem is about differente lengths of different files)

**Comment by nysthi** [comment] 2020-11-16 15:41
will be in 1.0.17

```## SUSSUDIO  
*	feature request: add contextual menu to avoid reset of playhead on keyframe change (#315)  
```

![Screen Shot 2020-11-16 at 16 39 20](https://user-images.githubusercontent.com/33201978/99274349-86c92a00-282a-11eb-8c87-3d06463b65bd.png)

**Comment by Eurikon** [comment] 2020-11-16 18:19
Sweet!! Thanks :D

**Closed** 2020-12-05 15:19 UTC
Labels: SOLVED, TO BE VERIFIED, VERIFIED, feature request
