### ISSUE TITLE
Big Button triggers... how to use?

### ISSUE THREAD

**Issue by jamshark70** [nysthi/nysthi#312] opened 2020-10-08 03:58 UTC
I have been unable to use Big Button successfully as a trigger. I can use it successfully as a gate.

I see three inputs and two outputs. These are not documented (no tooltips, no labels). I have no idea what differentiates them.

I've tried both of the outputs. The behavior is consistent for both.

- If I right click and set "output as a gate," every other click causes the sample-hold output to change. (I expected only the "gate-on" clicks to cause a change, so, this is OK.)

- If I right click and set output as a trigger, clicking the button does not cause the sample-hold output to change.

- If I connect an Aardvark clock generator and use the trigger output, the S&H does change. (So the S&H is being used correctly -- the problem must be with the big-button trigger.)

Is it that the trigger pulse is too short, or that the voltage is inappropriate? (For the latter, I played with nysthi "scale and offset" but couldn't find any settings that cause the trigger to take effect.)

![nysthi-big-button](https://user-images.githubusercontent.com/318301/95413257-8309d400-095d-11eb-9b9e-141d6fdc5783.png)

**Comment by nysthi** [comment] 2020-10-15 16:54
thanks for the report
I'll check it

**Comment by nysthi** [comment] 2020-10-16 16:48
ok
you are using it WRONG way

and remember that socket in NYSTHI are generally COLOR coded
in this case the sequence is
left to right

1 PULSE IN
2 PULSE OUT
3 BRIDGE AUDIO/CV IN
4 BRIDGE AUDIO/CV OUT
5 GATE OUT

if the button is in PULSE mode (not GATE mode)
a pulse is coming out from 2
the pulse is 1 msec, compatible with all PULSE receivers

the `1 PULSE IN`  is used if you want to control the button from remote
the `2 PULSE OUT` is the pulse out to USE

the `3 BRIDGE AUDIO/CV IN` and `4 BRIDGE AUDIO/CV OUT` is a bridge that is connected if the button is in GATE mode and is ACTIVE

the `5 GATE OUT` is the GATE out, 10V signal is output if BUTTON is in GATE mode and is ON (red)


closing, not a bug

**Closed by nysthi** 2020-10-16 16:48 UTC
Labels: TO BE VERIFIED

**Comment by jamshark70** [comment] 2020-10-17 07:00
Thanks for the explanation, it's clear.

I'm not sure where I was supposed to read about nysthi's color coding... such as, I just checked bigbutton.md in the manual project, but it's a stub.

In any case, no problem now, thanks for clearing it up.

**Comment by nysthi** [comment] 2020-10-17 07:58
@jamshark70 
courtesy of @patman023 

![inputoutput](https://user-images.githubusercontent.com/33201978/96331660-52adee00-105f-11eb-84c1-296aa0c01c14.png)
