### ISSUE TITLE
saving opening duplicated supersimplers loads wrong samples

### ISSUE THREAD

**Issue by jeremywen** [nysthi/nysthi#1] opened 2017-11-22 01:14 UTC
## Steps

1. start with a new patch
2. add supersimpler
3. duplicate that module
4. load a different sample into the first slot of both.
5. close Rack (saved to autosave.vcv)
6. open Rack

## actual result

the samples in the first slot will now be the same sample

## expected result

they should load the correct samples that they were saved with

**Comment by nysthi** [comment] 2017-11-22 07:06
Great catch!
I'll check! Thank you
probably the problem is for the simpler too...

**Comment by nysthi** [comment] 2017-11-22 07:07
probably I forgot about duplication: they share the same ID... :)

**Comment by nysthi** [comment] 2017-11-22 08:41
can't be solved, we need a new event from VCV Rack (at least 2 onVoluntaryDelete (when the user is deleting from menu) and  onClone)

**Comment by nysthi** [comment] 2017-11-22 08:55
https://github.com/VCVRack/Rack/issues/425

**Comment by nysthi** [comment] 2017-11-24 17:50
we need to wait for the rack 0.6.0
I need a "Clone" message to differentiate (Andrew knows about it)

**Comment by jeremywen** [comment] 2017-11-24 18:07
👍

**Comment by nysthi** [comment] 2018-01-11 10:52
still waiting for the API change

**Comment by VSpellbound** [comment] 2018-04-06 19:17
Hi!

Can this be fixed in v 0.6 ?

**Comment by nysthi** [comment] 2018-04-07 20:13
@VSpellbound @jeremywen  should be solved in
https://github.com/nysthi/nysthi/releases/tag/v0.6.2

**Closed by nysthi** 2018-04-07 20:13 UTC
Labels: bug

**Comment by VSpellbound** [comment] 2018-04-08 06:52
thanks!
